import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { CartContextProvider } from "@/context/CartContext";
import Backdrop from "@/components/ui/Backdrop";
import SearchItemInput from "@/components/ui/SearchItemInput";
import { SearchContextProvider } from "@/context/SearchContext";
import { AccountModalProvider } from "@/context/ModalContext";
import { EditProfileModalProvider } from "@/context/ModalContext";
import EditProfileClient from "@/components/layout/user/EditProfileClient";
import { ProfileModalProvider } from "@/context/ModalContext";
import { Toaster } from "react-hot-toast";
import { CartProvider } from "@/context/cartItemContext";
import { prisma } from '@/lib/server/prisma'
import { getUserSession } from '@/lib/server/getUserSession'
import AdminHeader from "@/components/layout/admin/AdminHeader";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const session = await getUserSession()
  const isAdmin = session?.user?.id
    ? await prisma.user.findUnique({
      where: { id: session.user.id },
    })
    : null
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <Toaster />
        <SearchContextProvider>
          <CartContextProvider>
            <ProfileModalProvider>
              <AccountModalProvider>
                <EditProfileModalProvider>


                  <CartProvider>
                    <div className="min-h-screen flex flex-col">
                      <div>
                        {
                          isAdmin?.role === "admin" ?
                            <>
                              <AdminHeader />
                            </>
                            : <Header isUserAdmin={false} />
                        }
                        {/* {isAdmin?.role === 'admin' ? <AdminHeader /> : <Header isUserAdmin={false} />} */}
                        <main className="grow relative">
                          <EditProfileClient />
                          <Backdrop />
                          <SearchItemInput />
                          {children}
                        </main>
                      </div>

                      <Footer />
                    </div>
                  </CartProvider>

                </EditProfileModalProvider>
              </AccountModalProvider>
            </ProfileModalProvider>
          </CartContextProvider>
        </SearchContextProvider>
      </body>

    </html>
  );
}
