import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { CartContextProvider } from "@/context/CartContext";
import Backdrop from "@/components/ui/Backdrop";
import SearchItemInput from "@/components/ui/SearchItemInput";
import { SearchContextProvider } from "@/context/SearchContext";
import { AccountModalProvider } from "@/context/ModalContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <SearchContextProvider>
          <CartContextProvider>
            <AccountModalProvider>
              <div className="min-h-screen flex flex-col">
                <div>
                  <Header />
                  <main className="grow relative">
                    <Backdrop />
                    <SearchItemInput />
                    {children}
                  </main>
                </div>

                <Footer />
              </div>
            </AccountModalProvider>
          </CartContextProvider>
        </SearchContextProvider>
      </body>

    </html>
  );
}
