import { ProductInterface } from "@/types/product";

export const fakeProductsData: ProductInterface[] = [
    {
        id: "1",
        name: "Classic Denim Jacket",
        isActive: true,
        description: "Timeless classic denim jacket with a modern fit.",
        price: 89.99,
        discountPrice: 69.99,
        isOutOfStock: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        categoryId: null,
        image:
            "https://images.unsplash.com/photo-1667636430259-9cf6d0008c24?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDl8fHxlbnwwfHx8fHw%3D",
    },
    {
        id: "2",
        name: "Yellow Summer Dress",
        isActive: true,
        description: "Bright and cheerful dress perfect for summer days.",
        price: 79.99,
        discountPrice: null,
        isOutOfStock: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        categoryId: null,
        image:
            "https://images.unsplash.com/photo-1671097828702-e0b4950a547c?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8eWVsbG93JTIwZHJlc3N8ZW58MHx8MHx8fDA%3D",
    },
    {
        id: "3",
        name: "Elegant Evening Gown",
        isActive: true,
        description: "Perfect gown for formal events and parties.",
        price: 129.99,
        discountPrice: 99.99,
        isOutOfStock: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        categoryId: null,
        image:
            "https://images.unsplash.com/photo-1673944586775-9b2d866f21b6?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDI3fHx8ZW58MHx8fHx8",
    },
    {
        id: "4",
        name: "Casual Cotton Tee",
        isActive: true,
        description: "Comfortable cotton tee for everyday wear.",
        price: 29.99,
        discountPrice: null,
        isOutOfStock: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        categoryId: null,
        image:
            "https://images.unsplash.com/photo-1603344593210-93e594695e51?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDI2fHx8ZW58MHx8fHx8",
    },
    {
        id: "5",
        name: "Vintage Denim Look",
        isActive: true,
        description: "Retro-inspired denim for a vintage look.",
        price: 94.99,
        discountPrice: 74.99,
        isOutOfStock: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        categoryId: null,
        image:
            "https://images.unsplash.com/photo-1667636430259-9cf6d0008c24?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDl8fHxlbnwwfHx8fHw%3D",
    },
    {
        id: "6",
        name: "Sunny Day Dress",
        isActive: true,
        description: "Light and breezy dress perfect for sunny days.",
        price: 84.99,
        discountPrice: 64.99,
        isOutOfStock: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        categoryId: null,
        image:
            "https://images.unsplash.com/photo-1671097828702-e0b4950a547c?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8eWVsbG93JTIwZHJlc3N8ZW58MHx8MHx8fDA%3D",
    },
    {
        id: "7",
        name: "Luxe Party Dress",
        isActive: true,
        description: "Stylish dress for upscale parties and events.",
        price: 149.99,
        discountPrice: null,
        isOutOfStock: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        categoryId: null,
        image:
            "https://images.unsplash.com/photo-1673944586775-9b2d866f21b6?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDI3fHx8ZW58MHx8fHx8",
    },
    {
        id: "8",
        name: "Basic Comfort Shirt",
        isActive: true,
        description: "Simple and comfy shirt for everyday use.",
        price: 34.99,
        discountPrice: 24.99,
        isOutOfStock: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        categoryId: null,
        image:
            "https://images.unsplash.com/photo-1603344593210-93e594695e51?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDI2fHx8ZW58MHx8fHx8",
    },
    {
        id: "9",
        name: "Premium Denim Jacket",
        isActive: true,
        description: "High-quality denim jacket with a premium feel.",
        price: 99.99,
        discountPrice: null,
        isOutOfStock: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        categoryId: null,
        image:
            "https://images.unsplash.com/photo-1667636430259-9cf6d0008c24?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDl8fHxlbnwwfHx8fHw%3D",
    },
    {
        id: "10",
        name: "Sunshine Yellow Outfit",
        isActive: true,
        description: "Cheerful yellow outfit perfect for sunny days.",
        price: 72.99,
        discountPrice: 54.99,
        isOutOfStock: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        categoryId: null,
        image:
            "https://images.unsplash.com/photo-1671097828702-e0b4950a547c?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8eWVsbG93JTIwZHJlc3N8ZW58MHx8MHx8fDA%3D",
    },
];
